services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /home/amsaleh/data/wordpress:/var/www/wordpress
    secrets:
      - nginx_private_key
      - nginx_crt
    env_file:
      - .env
    networks:
      - webnetwork
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - /home/amsaleh/data/wordpress:/var/www/wordpress
    networks:
      - webnetwork
      - dbnetwork
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    secrets:
      - mariadb_root_pass
      - mariadb_wordpress_pass
    volumes:
      - /home/amsaleh/data/mariadb:/var/lib/mysql
    networks:
      - dbnetwork
    restart: unless-stopped

networks:
  webnetwork:
    name: webnetwork
    driver: "bridge"
  dbnetwork:
    name: dbnetwork
    driver: "bridge"

secrets:
  nginx_crt:
    file: ../secrets/amsaleh.42.fr.crt
  nginx_private_key:
    file: ../secrets/amsaleh.42.fr.key
  mariadb_root_pass:
    file: ../secrets/mariadb_root_pass
  mariadb_wordpress_pass:
    file: ../secrets/mariadb_wordpress_pass