services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    secrets:
      - nginx_private_key
      - nginx_crt
    env_file:
      - .env
    restart: unless-stopped
  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - /home/amsaleh/data/mariadb-data:/var/lib/mysql
    restart: unless-stopped

secrets:
  nginx_crt:
    file: ../secrets/amsaleh.42.fr.crt
  nginx_private_key:
    file: ../secrets/amsaleh.42.fr.key