services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      wordpress:
        condition: service_healthy
      adminer:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - /home/amsaleh/data/wordpress:/var/www/wordpress
    secrets:
      - nginx_private_key
      - nginx_crt
    env_file:
      - .env
    networks:
      - webnetwork_wp
      - webnetwork_adminer
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    secrets:
      - mariadb_wordpress_pass
      - wordpress_admin_pass
      - wordpress_user0_pass
      - redis_server_pass
    volumes:
      - /home/amsaleh/data/wordpress:/var/www/wordpress
      - /home/amsaleh/data/adminer:/var/www/adminer
    env_file:
      - .env
    networks:
      - webnetwork_wp
      - dbnetwork_wp
      - fpm_adminer
      - redisnetwork
    healthcheck:
      test: ["CMD-SHELL", "cgi-fcgi -bind -connect 127.0.0.1:9000"]
      interval: 2s
      timeout: 2s
      retries: 30
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    secrets:
      - mariadb_root_pass
      - mariadb_wordpress_pass
    volumes:
      - /home/amsaleh/data/mariadb:/var/lib/mysql
    networks:
      - dbnetwork_wp
      - dbnetwork_adminer
    healthcheck:
      test: ["CMD-SHELL", "[ -f /tmp/mariadb-ready ] && mariadb-admin ping -uroot > /dev/null 2>&1"]
      interval: 2s
      timeout: 2s
      retries: 30
    restart: unless-stopped
  proftpd:
    container_name: proftpd
    build: ./requirements/bonus/proftpd
    ports:
      - 20-21:20-21
      - 60000-60150:60000-60150
    secrets:
      - proftpd_login0_pass
    volumes:
      - /home/amsaleh/data/wordpress:/var/www/wordpress
    env_file:
      - .env
    restart: unless-stopped
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    depends_on:
      wordpress:
        condition: service_healthy
    secrets:
      - nginx_private_key
      - nginx_crt
    volumes:
      - /home/amsaleh/data/adminer:/var/www/adminer
    env_file:
      - .env
    networks:
      - webnetwork_adminer
      - fpm_adminer
      - dbnetwork_adminer
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider 127.0.0.1"]
      interval: 2s
      timeout: 2s
      retries: 30
    restart: unless-stopped
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    secrets:
      - redis_server_pass
    networks:
      - redisnetwork
    healthcheck:
      test: ["CMD-SHELL", "redis-healthcheck.sh"]
      interval: 2s
      timeout: 2s
      retries: 30
    restart: unless-stopped

networks:
  webnetwork_wp:
    name: webnetwork_wp
    driver: "bridge"
  dbnetwork_wp:
    name: dbnetwork_wp
    driver: "bridge"
  webnetwork_adminer:
    name: webnetwork_adminer
    driver: "bridge"
  fpm_adminer:
    name: fpm_adminer
    driver: "bridge"
  dbnetwork_adminer:
    name: dbnetwork_adminer
    driver: "bridge"
  redisnetwork:
    name: redisnetwork
    driver: "bridge"

secrets:
  nginx_crt:
    file: ../secrets/amsaleh.42.fr.crt
  nginx_private_key:
    file: ../secrets/amsaleh.42.fr.key
  mariadb_root_pass:
    file: ../secrets/mariadb_root_pass
  mariadb_wordpress_pass:
    file: ../secrets/mariadb_wordpress_pass
  wordpress_admin_pass:
    file: ../secrets/wordpress_admin_pass
  wordpress_user0_pass:
    file: ../secrets/wordpress_user0_pass
  proftpd_login0_pass:
    file: ../secrets/proftpd_login0_pass
  redis_server_pass:
    file: ../secrets/redis_server_pass