services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - /home/amsaleh/data/wordpress:/var/www/wordpress
    secrets:
      - nginx_private_key
      - nginx_crt
    env_file:
      - .env
    networks:
      - webnetwork
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    secrets:
      - mariadb_wordpress_pass
      - wordpress_admin_pass
      - wordpress_user0_pass
    volumes:
      - /home/amsaleh/data/wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - webnetwork
      - dbnetwork
    healthcheck:
      test: ["CMD-SHELL", "[ -f /tmp/wordpress-ready ] && cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 30
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    secrets:
      - mariadb_root_pass
      - mariadb_wordpress_pass
    volumes:
      - /home/amsaleh/data/mariadb:/var/lib/mysql
    networks:
      - dbnetwork
    healthcheck:
      test: ["CMD-SHELL", "[ -f /tmp/mariadb-ready ] && mariadb-admin ping -uroot > /dev/null 2>&1 || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 30
    restart: unless-stopped

networks:
  webnetwork:
    name: webnetwork
    driver: "bridge"
  dbnetwork:
    name: dbnetwork
    driver: "bridge"

secrets:
  nginx_crt:
    file: ../secrets/amsaleh.42.fr.crt
  nginx_private_key:
    file: ../secrets/amsaleh.42.fr.key
  mariadb_root_pass:
    file: ../secrets/mariadb_root_pass
  mariadb_wordpress_pass:
    file: ../secrets/mariadb_wordpress_pass
  wordpress_admin_pass:
    file: ../secrets/wordpress_admin_pass
  wordpress_user0_pass:
    file: ../secrets/wordpress_user0_pass